export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CATEGORY_LOADING = "CATEGORY_LOADING";

export const ADD_SUPPLIER = "ADD_SUPPLIER";
export const UPDATE_SUPPLIER = "UPDATE_SUPPLIER";
export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const GET_SUPPLIER_BY_ID = "GET_SUPPLIER_BY_ID";
export const DELETE_SUPPLIER = "DELETE_CATEGORY";
export const SUPPLIER_LOADING = "SUPPLIER_LOADING";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_PRODUCT_BY_FILTERS = "GET_PRODUCT_BY_FILTER";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_LOADING = "PRODUCT_LOADING";

export const GET_ERRORS = "GET_ERRORS";


